### ISSUE TITLE
Unique survey ID returned with each question response

### ISSUE THREAD

**Issue by ryansdowning** [gzhihongwei/bias-in-facial-recognition#43]
Currently the form returns (prints) the response time, question number, and user's answer. In addition to this we will need to have a unique id that represents the user completing the survey that is returned with each form response. I'm not sure how to best generate this unique id (uuid4 comes to mind), but this is necessary because when I am inserting (question_num, reponse_time, response) to the database, it will not be very useful if we cannot map the question responses to the user who answered them.

**Comment by gzhihongwei** [comment]
I'm assuming that there is a table storing the users, so we could use the id of the next user that will be inserted as the unique ID. This can be put into `session` once a user navigates either to `/verification/` or `/identificiation/` and create a new entry in the table theen. That way, we can just access say `session['user_id']` or something on POST.

**Comment by rmattson1008** [comment]
There's a simple solution on Survey-ID, without using `session` yet. With uuid, the likelihood of collision should be pretty small.  We could also use a timestamp to generate an ID.
